scrape_configs:
  - job_name: 'producer-application'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s # This can be adjusted based on our needs
    static_configs:
      - targets: ['host.docker.internal:8080', 'host.docker.internal:8084', 'host.docker.internal:8090'] 
